version: '3.4'

services:
  qms:
    image: qms
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6:6
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'index.js']
